version: 2.1

jobs:
#  py310:
#    machine:
#      image: ubuntu-2004:202104-01
#    resource_class: arm.medium
#    steps:
#      - run: |
#          git clone https://github.com/KumaTea/tensorflow-aarch64
#          cd tensorflow-aarch64
#          sudo bash test/test.sh python3.10
#
#      - store_artifacts:
#          path: /tmp/artifacts

  py39:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: arm.medium
    steps:
      - run: |
          sudo apt update
          git clone https://github.com/KumaTea/tensorflow-aarch64
          cd tensorflow-aarch64
          sudo bash test/test.sh python3.9

      - store_artifacts:
          path: /tmp/artifacts

  py38:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: arm.medium
    steps:
      - run: |
          git clone https://github.com/KumaTea/tensorflow-aarch64
          cd tensorflow-aarch64
          sudo bash test/test.sh python3.8

      - store_artifacts:
          path: /tmp/artifacts

  py37:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: arm.medium
    steps:
      - run: |
          git clone https://github.com/KumaTea/tensorflow-aarch64
          cd tensorflow-aarch64
          sudo bash test/test.sh python3.7

      - store_artifacts:
          path: /tmp/artifacts

  py36:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: arm.medium
    steps:
      - run: |
          git clone https://github.com/KumaTea/tensorflow-aarch64
          cd tensorflow-aarch64
          sudo bash test/test.sh python3.6

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  build:
    jobs:
      # - py310
      - py39
      - py38
      - py37
      - py36
